name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.platform }} / Xcode ${{ matrix.xcode || matrix.container }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS
          - platform: macOS
            os: macos-26
            xcode: "26.2"

          # # iOS
          # - platform: iOS
          #   os: macos-26
          #   xcode: "26.2"
          #   destination: "platform=iOS Simulator,name=iPhone 17 Pro,OS=26.2"

          # # tvOS
          # - platform: tvOS
          #   os: macos-26
          #   xcode: "26.2"
          #   destination: "platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=26.2"

          # # watchOS
          # - platform: watchOS
          #   os: macos-26
          #   xcode: "26.2"
          #   destination: "platform=watchOS Simulator,name=Apple Watch Series 11 (46mm),OS=26.2"

          # # visionOS
          # - platform: visionOS
          #   os: macos-26
          #   xcode: "26.2"
          #   destination: "platform=visionOS Simulator,name=Apple Vision Pro,OS=26.2"

          # Linux
          - platform: Linux
            os: ubuntu-24.04
            container: "swift:6.2.3-noble"

    container: ${{ matrix.container }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        if: runner.os == 'macOS'
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

      - name: Show Swift version
        run: swift --version

      - name: Build with Swift
        run: swift build

      - name: Test with Swift (Desktop platforms)
        if: matrix.platform == 'macOS' || matrix.platform == 'Linux'
        continue-on-error: ${{ matrix.platform == 'macOS' }}
        run: swift test

      - name: Build with Xcode
        if: runner.os == 'macOS'
        run: |
          xcodebuild build-for-testing \
            -scheme SwiftPizzaSnips \
            -destination "${{ matrix.destination }}" \
            -enableCodeCoverage YES \
            | xcpretty

      - name: Test with Xcode
        if: runner.os == 'macOS'
        run: |
          xcodebuild test-without-building \
            -scheme SwiftPizzaSnips \
            -destination "${{ matrix.destination }}" \
            -enableCodeCoverage YES \
            | xcpretty
